# Generated by Django 4.2.3 on 2023-07-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_is_available_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='colour',
            field=models.CharField(max_length=50),
        ),
    ]
