# Generated by Django 4.2.4 on 2023-08-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_rename_strt_date_offer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
    ]
