# Generated by Django 4.2.4 on 2023-08-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offer_end_date_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(),
        ),
    ]
