# Generated by Django 4.2.4 on 2023-08-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_offer_end_date_alter_offer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_percentage',
        ),
    ]
