# Generated by Django 4.2.4 on 2023-08-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_remove_offer_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_percentage',
            field=models.FloatField(default=1.6),
        ),
    ]
