# Generated by Django 4.2.4 on 2023-08-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_offer_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.FloatField(),
        ),
    ]
