# Generated by Django 4.2.3 on 2023-07-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='email',
        ),
    ]
