# Generated by Django 4.2.3 on 2023-07-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_useraddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_name',
            field=models.CharField(default='dd', max_length=50),
        ),
    ]
