# Generated by Django 4.2.3 on 2023-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='jk', max_length=50),
        ),
    ]
