# Generated by Django 4.2.4 on 2023-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productvariant_created_at'),
        ('banner', '0002_banner_created_at_banner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ManyToManyField(related_name='banners', to='product.product'),
        ),
    ]
