# Generated by Django 4.2.4 on 2023-08-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_banner_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='product',
            new_name='products',
        ),
    ]
